token_server:
  host: localhost
  port: 8080
user_server:
  host: localhost
  port: 8080
mysql:
  user: xxx
  password: xxx
  host: localhost
  port: 3306
  database: account
redis:
  user: xxx
  password: xxx
  host: xxx
  port: 3306
  database: 0
