name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      FETCH_SOURCE: remote:https://github.com/writethesky/basic-proto.git
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Tools
      run: make install-tools
    - name: Generate
      run: make generate
    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -v -o basic main.go

    - name: Test
      run: go test -v ./...

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: basic
        path: basic
